---
title: 'Dashboard Project: Milestone I'
subtitle: 'Data Warehousing and Business Intelligence - Computing Lab'
author: 
- "Ivan Vallejo Vall, Saurav Poudel & Daniel Velásquez Vergara"
date: "October 14, 2016"
header-includes:
output:
  pdf_document:
    fig_caption: no
    highlight: kate
    keep_tex: no
    number_sections: yes
  html_document:
    highlight: kate
    md_extensions: +raw_tex+multiline_tables
    theme: united
    toc: yes
    toc_depth: 2
  rmarkdown::tufte_handout:
    highlight: kate
    keep_tex: no
    md_extensions: +raw_tex+multiline_tables
  tufterhandout::html_tufte_handout:
    highlight: kate
    keep_md: no
    md_extensions: +raw_tex+multiline_tables
    theme: united
    toc: yes
    toc_depth: 2
fontsize: 12pt
linkcolor: blue
---


```{r, knitr_options, include=FALSE}
    
    # loading in required packages
    if (!require("knitr")) install.packages("knitr"); library(knitr)
    if (!require("rmarkdown")) install.packages("rmarkdown"); library(rmarkdown)
    # some useful global defaults
    opts_chunk$set(warning=FALSE, message=FALSE, include=TRUE, echo=TRUE, cache=TRUE, cache.comments=FALSE, comment='##')

    # output specific defaults
    output <- opts_knit$get("rmarkdown.pandoc.to")
    if (output=="html") opts_chunk$set(fig.width=10, fig.height=5)
    if (output=="latex") opts_chunk$set(fig.width=6,  fig.height=4, 
        dev = 'png', dev.args=list(family="Arial"))
```

# Objective

The objective of the project is to produce analytics to inform policy makers and development banks about telecommunication development and guide their investments in the sector. 

# Dataset 
 
* Data from the International Telecommunication Union (ITU) on service uptake by country, available at <http://www.itu.int/en/ITU-D/Statistics/Pages/stat/default.aspx> (Excel format). Data cover 15 years and more than 200 countries for four selected indicators;

* Macroeconomic indicators by country from the World Bank open data website <http://data.worldbank.org>, accessible by means of an API (xml format). A subset of the over 600 indicators available will be selected according to their relevance vis-à-vis the telecommunication sector. 

* Google broadband pricing data for four years, available at <https://policybythenumbers.googleblog.com> (csv format). Data have a global coverage and include several operators per country, and for each operator the prices of diverse plans. 

# Analytics

The analysis of these data will be divided into two phases:

1. Modelling of the ITU telecom indicators using the World Bank's and Google's data. This will inform policy makers on the relation between the telecommunication indicators and certain macroeconomic measures and broadband prices in different countries;  

2. Forecasting future telecommunication development based on the models developed in (1) with a view to informing current investments from development banks (e.g. WB, IDB, EBRD-EIB). In particular, the analysis will try to identify countries will be worse off in terms of telecommunication development by 2020, thus helping allocate investment to those countries which need it most.