---
title: 'Dashboard Project: Milestone II'
subtitle: 'Data Warehousing and Business Intelligence - Computing Lab'
author: 
- "Ivan Vallejo Vall, Saurav Poudel & Daniel Velásquez Vergara"
date: "October 28, 2016"
header-includes:
output:
  pdf_document:
    fig_caption: no
    highlight: kate
    keep_tex: no
    number_sections: yes
  html_document:
    highlight: kate
    md_extensions: +raw_tex+multiline_tables
    theme: united
    toc: yes
    toc_depth: 2
  rmarkdown::tufte_handout:
    highlight: kate
    keep_tex: no
    md_extensions: +raw_tex+multiline_tables
  tufterhandout::html_tufte_handout:
    highlight: kate
    keep_md: no
    md_extensions: +raw_tex+multiline_tables
    theme: united
    toc: yes
    toc_depth: 2
fontsize: 12pt
linkcolor: blue
---


```{r, knitr_options, include=FALSE}
    
    # loading in required packages
    if (!require("knitr")) install.packages("knitr"); library(knitr)
    if (!require("rmarkdown")) install.packages("rmarkdown"); library(rmarkdown)
    # some useful global defaults
    opts_chunk$set(warning=FALSE, message=FALSE, include=TRUE, echo=TRUE, cache=TRUE, cache.comments=FALSE, comment='##')

    # output specific defaults
    output <- opts_knit$get("rmarkdown.pandoc.to")
    if (output=="html") opts_chunk$set(fig.width=10, fig.height=5)
    if (output=="latex") opts_chunk$set(fig.width=6,  fig.height=4, 
        dev = 'png', dev.args=list(family="Arial"))
```

# Analysis and Dashboard Views

An initial dashboard view will present the context of the project, i.e. the digital divide across countries and the effects it has in social and economic development. 

In order to illustrate the current situation worldwide, a map will be shown with countries colored according to the percentage of Internet users or some [alternative visualisation](geography.oii.ox.ac.uk/?page=internet-population-and-penetration).     
 
In addition, the first view will introduce the two types of analysis carried out to address the business questions (see 1.1 and 1.2) and link to them. 

## Analysis of the links between telecom and socio-economic development 
One or more selected indicators from the International Telecommunication Union (ITU) (e.g. percentage of Internet users) will be modelled based on the World Bank (WB) macroeconomic indicators and Google's broadband pricing data. The dependent variable will be the ITU indicator per country per year, and the independent/control variables will be selected from the WB and Google's datasets. 

Given the size of the possible explanatory variables (over 600 variables just in the WB database), statistical methods for variable selection (e.g. models based on singular value decomposition or strong regularization terms) will be explored in order to identify the subset of variables that have the most explanatory power.

In order to extract from the developed model some conclusions of relevance for policy-makers, econometric methods will be considered in order to deal with interpretation issues such as omitted variable bias, multicollinearity and correlation vs causality. 

A dashboard view will present the results of this section, including:

* __ITU indicator modelled and fit__. The result of the fitted model against the actual values for two years (e.g. 2005 and 2015). The outliers will be highlighted, so that policy-makers can easily identify those countries that are under- and outperforming the rest (e.g. with similar GDP p.c. have higher % Internet users). If some dynamism is possible in the chart, it will be incorporated (e.g. user can select the year for which the results are to be shown or can get some information on each datapoint when moving the pointer on it).

* __Explanatory variables__. List of the coefficients of the model (if many retained, just the most relevant), with some key statistical information for each of them in order to evaluate their significance and robustness.  

* __Top and bottom performers__. List of out- and underperformers, based on some aggregate calculation of the results of all years analysed (2000-2015).

* __Top and bottom performers__. Conclusions: a short text summarizing the results of the model and the main messages for policy-makers.


## Identification of the priority countries for telecom development aid  
ITU identifies annually a number of countries as being the world's least connected countries (LCCs) based on a combination of  telecommunication indicators for each country. About 40 countries are LCCs out of a total 165 countries with data available. 

Unfortunately, a number of developing countries do not produce telecommunication statistics, and therefore it is not known whether they are LCCs or not. For several of these countries data from the World Bank database and Google price benchmarking are available. 

These data will be used to develop a classification model in order to fill in the blanks in the map of LCCs. Because data availability will be reduced and limit the performance of the model, the results will be presented with some measure of uncertainty associated with the prediction.

The model will also be used to predict those countries that will be LCCs by 2020, with a view to helping development banks (e.g. WB, IDB) identify the countries most in need of aid. 

In order to predict the 2020 values, some rough assumptions will be made on the evolution of the variables used in the classification model. For instance, projecting them based on similar growth rates in 2015-2020 as in the previous five years and/or alternative scenarios.      

A dashboard view will present the results of this section, including:

* __Least Connected Countries 2016__. A global map with the LCCs highlighted. The results of the classification model will be marked, so that it is evident which previously unclassified countries are predicted to be LCCs and which not. The uncertainty of the predictions will be somehow represented graphically in the map.   
 
* __Least Connected Countries 2020__. Similar to the previous map, but with the predicted LCCs for 2020. The countries predicted to leave the LCC category in the period 2016-2020 will be highlighted to inform development banks of those countries that should not be a priority anymore. If there is more than one scenario, more than one map will be shown.    

* __Priority countries in 2016 and in 2020__. Conclusions: a short text summarizing the results of the classification model and the main messages to development banks and international agencies active in the area of telecommunication aid.